// <auto-generated />
namespace Mahamesh.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class init52 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init52));
        
        string IMigrationMetadata.Id
        {
            get { return "201909260929215_init52"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
