// <auto-generated />
namespace Mahamesh.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class init0073 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init0073));
        
        string IMigrationMetadata.Id
        {
            get { return "201908281400472_init0073"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
